on: ["push", "pull_request"]
name: Calculate Coverage

jobs:
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-home-cache-cleanup: true

      - name: Cache KMP tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-v1-${{ hashFiles('*.gradle.kts') }}

      - name: Test
        run: ./gradlew :arch:jvmTest

      - name: Generate coverage report
        run: ./gradlew arch:koverXmlReport

      - name: (Fail-only) Bundle test reports
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: (Fail-only) Upload the build report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: build-reports.zip

      - name: Update Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: arch/build/reports/kover/report.xml
          format: jacoco
          flagname: Unit